file:
    base:
        difi-statistikk: classpath:inndata-api-elasticsearch-local-key.txt
logging:
    level:
        'no':
            difi: INFO
        org: INFO
management:
    endpoints:
        web:
            base-path: /
'no':
    difi:
        statistics:
            elasticsearch:
                host: localhost
                port: 9200
spring:
    jackson:
        default-property-inclusion: NON_EMPTY
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://test1.maskinporten.no/
springdoc:
    swagger-ui:
        oauth:
            client-id: test
            client-secret: test2
