version: '3.5'

services:
  elasticsearch:
    image: ${REGISTRY}/statistics-elasticsearch:${VERSION}
    ports:
      - "9200:9200"
    command: bin/elasticsearch -Etransport.tcp.port=9301
    stop_grace_period: 5m
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch # only on first deploy, otherwise remove.
      - bootstrap.memory_lock=false # Fails in ondemand (windows and jenkins) if true.
    volumes:
      - statistics-local-data:/usr/share/elasticsearch/data
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  statistics-local-data:
    external: true
