# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test on non-main branches

on:
  push:
    branches-ignore:
      - main

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/eid-github-workflows/.github/workflows/maven-build.yml@main
    with:
      java-version: 17
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}